In [4]:
# *******Libraries*******
import numpy as np
import matplotlib.pyplot as plt

linear convolution

In [16]:
x=np.array([0,0,0,1,0,0,0,0]) 
m=len(x)
h=np.array([1,2,3,2,0]) 
n=len(h)

h=h.reshape(1,n)
h=np.fliplr(h)
#print(h)

y=np.zeros((m+2*(n-1)) ,dtype=int)
X=np.zeros((m+2*(n-1)) ,dtype=int)
X[n-1:n-1+m] = x

for i in range(len(X)-n):
    y[i]= np.dot(h,X[i:i+n])
    
print("full convolution result:")
print(y)

print('same convoluted result')
same=y[(n-1)//2:(n-1)//2+m]
same

full convolution result:
[0 0 0 1 2 3 2 0 0 0 0 0 0 0 0 0]
same convoluted result


array([0, 1, 2, 3, 2, 0, 0, 0])

In [5]:
# defining the filter/kernel  and the input
w=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
f=np.array([[0,0,0,0,0],
            [0,0,0,0,0],
            [0,0,1,0,0],
            [0,0,0,0,0],
            [0,0,0,0,0]])

In [6]:
# Image rotation by 180 degrees

def rot(img):
    img=img.T
    m,n=img.shape
    for i in range(m):
        for j in range(n//2):
            temp=img[i][j]
            img[i][j]=img[i][n-1-j]
            img[i][n-1-j]=temp
    return img

Function for 2-D 'full' and 'same' convolution

In [7]:
def  convn(f,w,conv_type):
    r,c=w.shape
    R,C=f.shape

    #flipping filter f by 180 for convolution
    w=np.flipud(w)
    w=np.fliplr(w)
    #w=rot(w)

    #creating empty output array 
    
    F=np.zeros((R+2*(r-1),C+2*(c-1)),dtype=int)
    out=np.zeros((R+2*(r-1),C+2*(c-1)),dtype=int)
    F[r-1:R+r-1,c-1:C+c-1]=f  #zero padding f  

    
    print("shape of final matrix: "+ str(out.shape))

    for i in range(out.shape[0]-r):
        for j in range(out.shape[1]-c):
            out[i+(r-1)//2][j+(c-1)//2]= np.sum(w * F[i:i+r,j:j+c])
    if conv_type =="full" :       
        print('full 2-D convolution')
        return out    # full parameter 
        
    elif conv_type =="same" :
        print('same 2-D convolution')
        same=out[r-1:R+r-1,c-1:C+c-1]
        return same
    

Function for Valid convolution

In [14]:
def valid_conv(x,h):
    M,N=x.shape
    m,n=h.shape
    
    h=np.flipud(h)
    h=np.fliplr(h)

    
    out=np.zeros((M-m+1,N-n+1))
    print("shape of final matrix" ,out.shape)
    for i in range(out.shape[0]):
        for j in range(out.shape[1]):
#             out[i+((m-1)//2)][j+((n-1)//2)] = x[i:i+m,j:j+n,:]*h
              out[i][j] = np.sum(h*x[i:i+m,j:j+n])
    out=out.astype("uint8")
    print("valid convolution: ")
    print(out)

Running the functions to find results

In [9]:
out=convn(f,w,"full")
print(out)

shape of final matrix: (9, 9)
full 2-D convolution
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0]
 [0 0 0 4 5 6 0 0 0]
 [0 0 0 7 8 9 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [10]:
out=convn(f,w,"same")
print(out)

shape of final matrix: (9, 9)
same 2-D convolution
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [15]:
valid_conv(f,w)

shape of final matrix (3, 3)
valid convolution: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
